src/extension/utils.js

Fix #9
- transform gh owner, repo and branch to lowercase when adding projects
- compare hlx urls to lowercase gh details in existing configs

fix: sidekick extension doesn't like uppercase gh

---

.circleci/config.yml
src/extension/utils.js

Fix #7 
Support any of the following URL formats:
```
https://adobe.sharepoint.com/:f:/r/sites/MySite/Shared%20Documents/website
https://adobe.sharepoint.com/sites/MySite/Shared%20Documents/website
```

fix: more leniency with URL format in mountpoint

---

src/extension/configpicker.js

With the latest sidekick CSS, the text on the config picker toolbar is hanging 10px too low.

fix: config picker text too low

---

src/extension/utils.js

- case-insensitive sharepoint site names (sharepoint uses both!)
- require `*.hlx.page` to have a ref

fix: more reliable project url detection

---

src/extension/app.css
src/extension/de.css
src/extension/fr.css
src/extension/module.js

Fix #119 
When a user clicks _preview_ in edit mode or _reload_ in preview mode, a hint to always pro-actively save the document in onedrive/sharepoint will be displayed.

feat: show save hint for onedrive

---

package-lock.json
package.json
src/extension/background.js
src/extension/content.js
src/extension/installhelper.js
src/extension/options.css
src/extension/options.html
src/extension/options.js
src/extension/sidekick.js
src/extension/utils.js
test/extension/chromeMock.js
test/extension/fetchMock.js
test/extension/utils.test.js

Fix #125 
- restructure project configs in sync storage:
- each project config is stored in its own storage property as `owner/repo`
- `hlxSidekickProjects` keeps an index of all project configs
- on startup, migrate existing `hlxSidekickConfigs` to new structure
other changes in this PR:
- display number of configured projects on options page
- renamed functions in `utils.js` and `options.js` for better differentiation between `config` and `project`
- enable WTR tests for `utils.js`

refactor: optimized storage structure and code cleanup

---

docs/config.schema.json
src/extension/module.js
test/module.test.js

When `passConfig: true`, url gets:
`&ref=...&repo=...&owner=...&host=...&project=...`

#167 Add ability to pass additional sk config info to url via passConfig param

---

.github/workflows/branch-release.yaml

We don't need to be able to preview the sidekick bookmarklet on `helix-website` for branches created by renovate.

chore: no branch release if renovate

---

src/bookmarklet/app.js
test/app.test.js
test/login.test.js

#159 
To test:
1. Turn off sidekick extension on `chrome://extensions`
2. Go to https://sidekick-issue-159--helix-website--adobe.hlx.live/tools/sidekick/
3. Enter a GH URL of a test project
4. Drag the white sidekick button to your toolbar
5. Navigate to a URL on your test project and click the bookmarklet

feat: show extension hint to bookmarklet users

---

src/extension/background.js

The "View Document Source" context menu item if the site in the current is a Franklin site: even if you have no config for it, it should be possible to view the source, i.e. we must "guess" if the site is ours. Check if `scripts.js`, `styles.css` and `main > div.section` should do the trick.

feat: show the View Document Source context menu item if site is a Franklin site

---

package.json
src/extension/app.css
src/extension/de.css
src/extension/fr.css
src/extension/module.js

Currently, if the user uploads a Microsoft Word Doc or a an Excel sheet, and does not convert it, the document is authorable in Google Doc/Sheets. When attempting to author, then publish such documents via sidekick, the message displayed says:
> "Previewing failed. Must be Google document or spreadsheet."
As a User, I did not, at first realize that a Microsoft Document and a Google Document are different and that only the latter is supported by helix. This PR shows a more helpful message and instructions to convert the document to a Google Doc/Sheet.

Better error messages for Word Docs and Excel Sheets [NEED TRANSLATION HELP]

---

src/extension/_locales/en/messages.json
src/extension/background.js
src/extension/view-doc-source/index.html
src/extension/view-doc-source/js/ui.js

Images are missing if the root path is not `/` (like https://www.adobe.com/express/).
Also align naming.

fix(view-doc-source): missing image when root path is not '/'

---

.nycrc.json
src/extension/module.js
test/module.test.js

Plugins not loading due to wrong value passed into `i18n`.
fixes #265

fix: pass sk instance to i18n

---

src/extension/_locales/de/messages.json
src/extension/_locales/fr/messages.json

Error in XCode cloud build: 
> ITMS-90862: Invalid messages file - The messages.json validation failed for locale de in the Safari web extension bundle AEM Sidekick.app/Contents/PlugIns/AEM Sidekick Extension.appex. The description field must be present, of string type, and 112 or fewer characters long.
> ITMS-90862: Invalid messages file - The messages.json validation failed for locale fr in the Safari web extension bundle AEM Sidekick.app/Contents/PlugIns/AEM Sidekick Extension.appex. The description field must be present, of string type, and 112 or fewer characters long.

chore: shorten de and fr descriptions

---

test/SidekickTest.js
test/extension/utils.test.js
test/module.test.js
test/utils.js

use custom user agent, and the code detecting the `alert` would work again
background: `@web/test-runner-chrome` uses the `new` headless mode since [PR 2269](https://github.com/modernweb-dev/web/pull/2269) which no longer inserts a `HeadlessChrome` into the user agent.

chore(test): use HeadlessChrome again

---

.nycrc.json
test/utils.js
web-test-runner.config.cjs

exports script coverage from puppeteer to c8 in a compatible format

chore(test): export c8 coverage from puppeteer

---

src/extension/background.js

When using the `loadSidekick` API, we do not expect the Sidekick to respect the display / hidden logic since there is no point of loading a hidden sidekick.

feat: display the sidekick when loading via the API

---

test/utils.js

when coverage was not requested (`process.env.NODE_V8_COVERAGE` is not set), then skip building and storing the coverage

chore(test): skip coverage step when not enabled

---

docs/config.schema.json

Redirect property allowing to load the sidekick configuration from a central place.

chore: add redirect property

---

src/extension/background.js

If the site does not use `scripts.js` or `styles.css`, `View document source` would not work. The only hard requirement which can even not be changed at project level is the `body > main > div` dom structure. We could restrict the guessing to this only.
Note: this could lead to false positive - a lot of sites are probably using a `body > main > div` structure. The display will then try his best to render a markdown from the non-helix site - result will not be accurate. But this could still be useful to visualise how the document could look like as a Word document (content and sections should appear, page metadata should be correct, only blocks would be missing).

feat: allow view doc source on customised sites

---

src/extension/options.js

Fix #652 
The trick is to use a nonsensical mime type to keep Safari from rendering it.

fix(safari): config export displays json in browser

---

src/extension/module.js
test/bulk-copy-urls.test.js
test/fixtures/admin-sharepoint-grid.html
test/fixtures/admin-sharepoint.html
test/module.test.js
test/utils.js

fix: filename with comma

---

src/extension/_locales/en/messages.json
src/extension/background.js
src/extension/options.html
src/extension/options.js
src/extension/utils.js
test/extension/utils.test.js

Allow the options page to define an authorization header for project-specific top-level browser requests. Required for sites with authentication enabled in helix 5.
Fixes #737

feat: support helix 5 authorization header in project config

---

src/extension/module.js
test/SidekickTest.js
test/publish.test.js

If the url contains a fragment the `nocache` query param should come before the fragment. Currently we are just appending it on to the url and not factoring in the edge cache where the url contains a fragment on `.page` and then is published.
fixes #750

fix: account for url's with fragments when adding nocache query param

---

src/extension/utils.js
test/extension/utils.test.js

The current implementation of the sidekick is only sending the authorization header for the main document, but not for the subresources (scripts, stylesheets, images, etc.).
This PR ensures that all subresources are loaded when helix 5 authentication is enabled and the page renders.
**Before:**
**After:**

fix: Authorization header is not sent for page subresources

---

src/extension/options.js

`sampleRUM` currently fails due to the missing sidekick object.

fix(rum): instrument options page

---

src/extension/module.js

fix: if v7 sidekick exists on page, don't open custom views
