- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/background.js
- src/extension/options.css
- src/extension/options.html
- src/extension/options.js
- src/extension/utils.js
Fix #13
- Only Helix 3 projects can be added
- Existing Helix 2 projects are shown with a warning:
> feat: remove hlx2 support

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/content.js
- src/extension/options.css
- src/extension/options.html
- src/extension/options.js
- src/extension/sidekick.js
- src/extension/utils.js
> feat: support admin version

- src/extension/options.js
Making sure an expanded area is scrolled into view.
> fix: scroll expanded option area into view

- src/extension/background.js
- src/extension/installhelper.js
- src/extension/options.js
- src/extension/utils.js
> feat: simplify adding project from share url

- src/extension/installhelper.js
> fix: share URL instrumentation not run

- src/extension/installhelper.js
Fix #22 
- capture `sidekickGeneratorReady` event (fired by the block) to avoid flickering of other containers
- make sure instrumentation runs whenever the `giturl` query parameter changes
> fix: unstable share URL instrumentation

- src/extension/utils.js
> fix: check for query param

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/background.js
- src/extension/options.css
- src/extension/options.html
- src/extension/options.js
- src/extension/sidekick.js
- src/extension/utils.js
> feat: show help content

- src/extension/configpicker.js
> fix(configpicker): close button regression

- src/extension/options.js
- src/extension/utils.js
> fix: support personal sharepoint mountpoints and fix preview urls in options

- src/extension/background.js
- src/extension/utils.js
> fix: reload page after adding project via context menu

- src/extension/utils.js
> fix(regression): sharepoint url support

- src/extension/options.css
- src/extension/options.js
Fix #48 
also fixes missing padding and adds an enter key handler.
> fix: edits of project configs not persisted

- src/extension/configpicker.js
- src/extension/content.js
- src/extension/options.js
> UX enhancements

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/content.js
- src/extension/options.html
- src/extension/options.js
- src/extension/sidekick.js
- src/extension/utils.js
> feat: invoke branch version of sidekick

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/content.js
- src/extension/options.html
- src/extension/options.js
- src/extension/sidekick.js
- src/extension/utils.js
> feat: remove legacy support

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/configpicker.js
- src/extension/options.html
- src/extension/options.js
- src/extension/sidekick.js
> UX improvements

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/background.js
- src/extension/options.css
- src/extension/options.js
- src/extension/utils.js
> feat: add projects from preview or live, disable projects

- .circleci/config.yml
- package-lock.json
- package.json
- src/extension/background.js
- src/extension/utils.js
- test/extension/chromeMock.js
- test/extension/utils.test.js
- 80% test converage for `utils.js`
- minor refactorings
> chore: utils tests

- src/extension/background.js
> fix: add project missing from context menu

- src/extension/_locales/fr/messages.json
Some few missing translations.
> chore: fr translations

- src/extension/background.js
- src/extension/manifest.json
- src/extension/sidekick.js
- src/extension/utils.js
listens for external messages and updates the config with the auth token.
> feat: use cookie-less auth

- src/extension/sidekick.js
- src/extension/utils.js
- test/extension/utils.test.js
> fix: support custom sharepoint domains

- .github/workflows/branch-release.yaml
- .github/workflows/release.yaml
- docs/config.schema.json
- src/extension/module.js
> feat: updated config schema

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/background.js
- src/extension/options.js
> feat: enable/disable project via contxt menu

- src/extension/background.js
- src/extension/installhelper.js
https://www.hlx.live/tools/sidekick/?giturl=https%3A%2F%2Fgithub.com%2Fadobe%2Fhelix-website%2Ftree%2Fmain
> feat: always use serviceworker when adding project

- src/extension/app.css
- src/extension/de.css
- src/extension/fr.css
- src/extension/module.js
- test/edit-preview.test.js
Fix #129 (port to `mv3` branch)
> feat: show save hint for onedrive

- CONTRIBUTING.md
- README.md
- package.json
- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/background.html
- src/extension/options.html
- src/extension/options.js
- test/extension/utils.test.js
> chore: rebrand helix to franklin (mv2)

- docs/API.md
- docs/config.schema.json
- src/extension/app.css
- src/extension/module.js
- test/SidekickTest.js
- test/module.test.js
> feat: palette plugins

- src/bookmarklet/app.js
- test/app.test.js
- test/module.test.js
> feat: bookmarklet to load config.json

- src/extension/module.js
> Add clipboard-write permission to palette iframe

- src/extension/module.js
> Fire ready event(s) after sk has been prepended

- src/extension/utils.js
- test/extension/utils.test.js
> feat: detect git clone url when adding project

- src/extension/options.js
> fix: exclude auth tokens from backup

- src/extension/module.js
- test/module.test.js
> fix: extend existing plugin

- src/bookmarklet/app.js
- src/extension/module.js
- src/extension/options.js
- src/extension/utils.js
- test/app.test.js
- test/extension/utils.test.js
- test/login.test.js
- test/module.test.js
Fix #159 via PR #163 
Fix #172 via PR #173 
Fix #165 via PR #174
Fix #150 via PR #175
> Minor release 2022-11-14

- src/extension/module.js
- src/extension/sidekick.js
- test/logout.test.js
> fix: login/logout flow

- src/extension/background.js
- src/extension/content.js
- src/extension/utils.js
- test/extension/fetchMock.js
- test/extension/utils.test.js
> feat: improved config matching algorithm

- src/extension/background.js
Fix https://github.com/adobe/helix-sidekick-extension/issues/193
> feat(view-doc-source): only for active tab

- src/extension/background.js
- src/extension/options.html
> fix: add project not shown with fresh config

- src/extension/app.css
- src/extension/de.css
- src/extension/fr.css
- src/extension/module.js
- test/module.test.js
Implements #179
Adds an info button next to the user profile that displays the last edited, last previewed and last published times for the page.
> feat: info button for last modified times

- .nycrc.json
- src/extension/module.js
- test/edit-preview.test.js
- test/login.test.js
> fix: user dropdown cleanup after logout

- .nycrc.json
- src/extension/app.css
- src/extension/de.css
- src/extension/fr.css
- src/extension/module.js
- test/edit-preview.test.js
- test/module.test.js
Fix #179 (continuation of #180)
> feat: show info button for last modified times

- src/extension/module.js
> fix: Error when previewing google doc or sheet

- .github/workflows/branch-release.yaml
- .github/workflows/release.yaml
> fix: bulk operations broken  in bookmarklet

- .github/workflows/branch-release.yaml
- .github/workflows/release.yaml
- src/extension/module.js
> fix(bookmarklet): relative import prohibited

- src/extension/app.css
- src/extension/module.js
- test/module.test.js
Also fix layout of info text that got moved around in #202
> Close menu when clicking the open icon

- src/extension/module.js
- test/module.test.js
> fix: 404 status error on new documents

- src/extension/module.js
> fix: language fallback failing

- src/extension/module.js
> fix: sidekick always shows login option

- src/extension/module.js
> fix: lower concurrency for bulk preview

- src/extension/module.js
> fix: login fails in admin env

- src/extension/module.js
- src/extension/options.js
- test/bulk-copy-urls.test.js
- test/bulk-info.test.js
- test/bulk-preview.test.js
- test/bulk-publish.test.js
> fix: multiple issues

- src/extension/background.js
View document source is not available for blog.adobe.com - rule is too strict.
> feat: relax view doc source constraint

- src/extension/module.js
> fix: undefined date should say never

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/module.js
> fix(bulk): special chars in folder or file names

- src/extension/module.js
- src/extension/options.js
Fix #231 
Fix #311
Fix #314 
Fix #315
> Various fixes

- docs/API.md
- docs/config.schema.json
- src/extension/module.js
> Fix #320 config.schema.json: add 'dev' as a plugins.environments option

- src/extension/module.js
- test/module.test.js
> fix: add wildcard to clipboard-write permissions

- src/extension/installhelper.js
> fix: share url instrumentation

- src/extension/utils.js
> fix: delete project not working in safari

- src/extension/background.js
> fix(safari): help content not displayed

- src/extension/module.js
> fix: don't set `credentials=include` when in devMode

- src/extension/module.js
- [x ] make sure to link the related issues in this description
- [x ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes
https://github.com/adobe/helix-sidekick-extension/issues/345 
> remove success console log

- src/extension/module.js
> fix: custom plugin handling

- src/extension/background.js
- src/extension/module.js
Fix #343
Fix #345
Fix #348 
Fix #350
> Fix 20230511

- src/extension/background.js
- src/extension/utils.js
- test/extension/utils.test.js
> feat: add project from sharepoint/gdrive url

- src/extension/background.js
- src/extension/module.js
- src/extension/utils.js
- test/edit-preview.test.js
- test/extension/utils.test.js
- test/publish.test.js
> Feat 20230515

- src/extension/module.js
- test/edit-preview.test.js
> fix: excel preview can fail the first time

- docs/API.md
- src/extension/module.js
- test/module.test.js
> feat: custom preview and live host

- src/extension/module.js
- src/extension/utils.js
- test/extension/fetchMock.js
- test/extension/utils.test.js
> feat: fetch status from sharepoint to help discover the correct project

- src/extension/content.js
> feat(configpicker): persist user choice for session

- src/extension/content.js
- src/extension/module.js
- src/extension/utils.js
- test/extension/fetchMock.js
- test/extension/utils.test.js
> Feat 20230525

- src/extension/background.js
- src/extension/options.js
- src/extension/utils.js
- test/extension.test.js
- test/extension/chromeMock.js
- test/extension/fetchMock.js
- test/extension/utils.test.js
> fix: add project for authenticated sites

- src/extension/module.js
- test/bulk-preview.test.js
- test/bulk-publish.test.js
- test/module.test.js
> fix: cannot override bulk plugins

- src/extension/background.js
- src/extension/module.js
- src/extension/options.js
- src/extension/utils.js
- test/bulk-preview.test.js
- test/bulk-publish.test.js
- test/extension.test.js
- test/extension/chromeMock.js
- test/extension/fetchMock.js
- test/extension/utils.test.js
- test/module.test.js
Fix https://github.com/adobe/helix-sidekick-extension/issues/373
Fix https://github.com/adobe/helix-sidekick-extension/issues/385
> Fix 20230530

- src/extension/module.js
> fix(regression): detect drive navigation

- test/login.test.js
- test/module.test.js
- test/utils.js
> chore: status attribute tests

- src/extension/_locales/en/messages.json
- src/extension/options.html
- src/extension/options.js
- src/extension/utils.js
- test/extension/fetchMock.js
> feat(options): configurable previewHost/liveHost

- src/extension/module.js
- src/extension/sidekick.js
> fix: wrong previewHost/liveHost handling

- src/extension/_locales/de/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko-kr/messages.json
- src/extension/_locales/pt-br/messages.json
- src/extension/_locales/zh-cn/messages.json
- src/extension/_locales/zh-tw/messages.json
> Translations on 2023-06-14

- package-lock.json
- package.json
- src/extension/module.js
> fix: detect admin env in personal folder

- package-lock.json
- package.json
- src/extension/_locales/en/messages.json
- src/extension/app.css
- src/extension/module.js
- test/module.test.js
> feat: encourage user to login

- src/extension/_locales/en/messages.json
- src/extension/view-doc-source/index.html
- src/extension/view-doc-source/js/ui.js
> fix(view-doc-source): missing i18n

- src/extension/module.js
- test/bulk-preview.test.js
- test/login.test.js
- test/logout.test.js
> feat: do not use loginRedirect

- src/extension/_locales/en/messages.json
- src/extension/module.js
> fix: hardcoded english strings in delete/unpublish

- .circleci/config.yml
- .mocha-multi.json
- package-lock.json
- package.json
- src/extension/background.js
- src/extension/options.js
- src/extension/utils.js
- test/extension/utils.test.js
> refactor: context menu handling

- src/extension/sidekick.js
> fix: missing mountpoint causes js error

- src/extension/module.js
> chore: remove status attribute

- src/extension/view-doc-source/js/ui.js
> fix: keep section breaks

- src/extension/background.js
- src/extension/utils.js
- test/extension/utils.test.js
- test/mocks/chromeMock.js
> fix: do not close sidekick if loaded externally

- src/extension/_locales/en/messages.json
- src/extension/background.js
- src/extension/module.js
- src/extension/utils.js
- test/delete.test.js
- test/extension/utils.test.js
- test/mocks/chromeMock.js
- test/unpublish.test.js
- test/utils.js
> Feat 20230814

- src/extension/utils.js
> fix: adjust sharelink for rootfolder requests

- src/extension/background.js
- src/extension/module.js
> feat: closePalette API

- src/extension/view/json/json.js
- test/unit/json.single.test.js
> fix: Render single sheet without a title

- src/extension/view/json/json.css
- src/extension/view/json/json.js
- test/fixtures/singlesheet.json
- test/unit/json.single.test.js
Fix #156 and replace https://github.com/adobe/helix-sidekick-extension/pull/506 (to be against `main`).
> fix: correct urls in json rendition

- src/extension/_locales/de/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko-kr/messages.json
- src/extension/_locales/pt-br/messages.json
- src/extension/_locales/zh-cn/messages.json
- src/extension/_locales/zh-tw/messages.json
Latest Adobe translations for helix-sidekick-extension
> Latest translations, all HT

- src/extension/background.js
- src/extension/module.js
- test/module.test.js
- test/utils.js
> feat: support aem.page and aem.live

- src/extension/app.css
- src/extension/module.js
- test/module.test.js
> feat: make login more discoverable

- docs/API.md
- docs/config.schema.json
- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko-kr/messages.json
- src/extension/_locales/pt-br/messages.json
- src/extension/_locales/zh-cn/messages.json
- src/extension/_locales/zh-tw/messages.json
- src/extension/app.css
- src/extension/background.js
- src/extension/module.js
- test/bulk-preview.test.js
- test/bulk-publish.test.js
- test/module.test.js
- test/preview.test.js
- test/utils.js
Fixes #511
Fixes #506
Fixes #504 
Fixes #496 
Fixes #156
Includes #503 
Includes #502
> Feat 20230906

- src/extension/_locales/en/messages.json
> fix: missing placeholders

- src/extension/_locales/en/messages.json
- src/extension/module.js
> fix: send detail object to custom event listeners

- package-lock.json
- package.json
- src/extension/module.js
see https://discord.com/channels/1131492224371277874/1155876756461457529/1155876756461457529
> fix(globs): don't match any character on .

- src/extension/module.js
- test/fixtures/admin-sharepoint.html
- test/publish.test.js
- test/reload.test.js
- ignore sharepoint folders in bulk selection
- re-add `json` as supported file extension
> Ignore sp folders

- docs/config.schema.json
- src/extension/module.js
> fix: exclude/includePath not working as expected

- src/extension/module.js
> fix: proper resource check

- src/extension/background.js
- src/extension/module.js
- src/extension/utils.js
- test/extension/utils.test.js
> feat: support for custom sharepoint domain

- docs/config.schema.json
> chore: add id property to specialView schema

- docs/config.schema.json
- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko-kr/messages.json
- src/extension/_locales/pt-br/messages.json
- src/extension/_locales/zh-cn/messages.json
- src/extension/_locales/zh-tw/messages.json
- src/extension/background.js
- src/extension/content.js
- src/extension/module.js
- src/extension/sidekick.js
- src/extension/utils.js
- test/extension.test.js
- test/logout.test.js
- test/user.test.js
- test/utils.js
Fix #539
Fix #563
Fix #566 
Fix #568
> feat-20231024

- src/extension/_locales/de/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko-kr/messages.json
- src/extension/_locales/pt-br/messages.json
- src/extension/_locales/zh-cn/messages.json
- src/extension/_locales/zh-tw/messages.json
> Latest translations

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko/messages.json
- src/extension/_locales/pt_BR/messages.json
- src/extension/_locales/zh_CN/messages.json
- src/extension/_locales/zh_TW/messages.json
- src/extension/view-doc-source/js/ui.js
Fix https://github.com/adobe/helix-sidekick-extension/issues/530
> chore: localize view doc source copy button

- src/extension/background.js
- src/extension/view-doc-source/js/blocks.js
- make "is franklin site" check more DOM specific
- make doc source computation logic more resilient
> feat(view-doc-source): add site detection to be more precise and resilient

- .github/workflows/release.yaml
- src/bookmarklet/app.js
- src/extension/manifest.json
- src/extension/module.js
- src/extension/rum.js
- src/extension/view-doc-source/js/ui.js
- test/SidekickTest.js
Add rum tracking for:
- edit button
- info button
- view-doc-source is opened
- view-doc-source is copied
@trieloff could you please validate the 2 sampleRUM calls ?
> feat: improve instrumentation

- src/extension/module.js
- test/fixtures/admin-sharepoint-grid.html
- test/fixtures/admin-sharepoint.html
> fix(bulk): pinned files break selection

- src/extension/background.js
- src/extension/module.js
- src/extension/sidekick.js
- src/extension/utils.js
- test/extension/utils.test.js
- test/logout.test.js
- test/user.test.js
- use tighter host checks to prevent triggering sidekick from malicious hosts
- do not handle auth token outside of service worker
> fix: tighten security

- src/extension/background.js
> fix: do not modify user agent

- src/extension/module.js
> feat: new event "previewed"

- docs/config.schema.json
- src/extension/module.js
- test/module.test.js
> feat: always fire custom event

- src/extension/_locales/en/messages.json
- test/module.test.js
> fix: 403 error message

- src/extension/module.js
- test/module.test.js
> fix: language detection

- src/extension/view-doc-source/js/ui.js
> fix: create a minimal config for sampleRUM

- src/extension/utils.js
- test/extension/utils.test.js
> fix: fix logger src file

- package-lock.json
- package.json
- src/extension/_locales/de/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko/messages.json
- src/extension/_locales/pt_BR/messages.json
- src/extension/_locales/zh_CN/messages.json
- src/extension/_locales/zh_TW/messages.json
- src/extension/module.js
- src/extension/utils.js
- test/extension/utils.test.js
> Feat 20240109

- src/extension/module.js
> fix: detect sharepoint folder URL with RootFolder param

- src/extension/module.js
- src/extension/options.js
- test/bulk-copy-urls.test.js
- test/bulk-info.test.js
- test/bulk-preview.test.js
- test/bulk-publish.test.js
- test/fixtures/admin-gdrive.html
- test/fixtures/admin-sharepoint.html
> fix: single file selection should not trigger bulk operation

- src/extension/options.js
> fix: extra project creation for invalid gitURL

- src/extension/background.js
#670 
RUM data collection for context menu items
> feat: RUM data collection for context menu items

- src/extension/_locales/en/messages.json
- src/extension/background.js
- src/extension/module.js
- src/extension/options.js
- test/module.test.js
Fix #591
Fix #595 
Fix #596 
Fix #670
Fix #675
> Fix 20240226

- src/extension/_locales/de/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko/messages.json
- src/extension/_locales/pt_BR/messages.json
- src/extension/_locales/zh_CN/messages.json
- src/extension/_locales/zh_TW/messages.json
> Translations Update, please integrate

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko/messages.json
- src/extension/_locales/pt_BR/messages.json
- src/extension/_locales/zh_CN/messages.json
- src/extension/_locales/zh_TW/messages.json
- src/extension/background.js
- src/extension/options.js
- src/extension/utils.js
- test/extension/utils.test.js
- test/mocks/chromeMock.js
Fix #665
Fix #688 
Fix #698
Fix #700
> chore: validate content URL

- src/extension/module.js
- test/fixtures/admin-sharepoint-grid.html
- test/fixtures/admin-sharepoint.html
> fix: bulk selection in non-english sharepoint

- src/extension/background.js
- src/extension/module.js
- src/extension/utils.js
- test/extension/utils.test.js
- test/fixtures/admin-sharepoint-grid.html
- test/fixtures/admin-sharepoint.html
> feat: 20240418 release

- src/extension/module.js
- test/module.test.js
> Fix: Allow local sourcing of urls during dev.

- src/extension/background.js
- src/extension/module.js
- test/fixtures/admin-gdrive-grid.html
- test/fixtures/admin-gdrive.html
- test/module.test.js
Fix #590 
Fix #664
Fix #716
Fix #724
> fix(bulk): gdrive selection broken due to recent dom change

- .nycrc.json
- src/extension/_locales/en/messages.json
- src/extension/module.js
- test/bulk-copy-urls.test.js
- test/bulk-preview.test.js
- test/delete.test.js
- test/edit-preview.test.js
- test/module.test.js
- test/publish.test.js
- test/reload.test.js
- test/unpublish.test.js
> feat: improve error handling

- docs/config.schema.json
- src/extension/utils.js
- test/extension.test.js
- test/extension/utils.test.js
- test/mocks/fetchMock.js
> feat: add project should fetch from config.json

- src/extension/module.js
- test/fixtures/admin-gdrive.html
> fix(bulk): broken gdrive type detection

- docs/config.schema.json
- src/extension/utils.js
- test/extension.test.js
- test/mocks/fetchMock.js
> feat: mountpoint deprecated in config.json

- docs/config.schema.json
- src/extension/module.js
- src/extension/utils.js
- test/extension.test.js
- test/fixtures/admin-gdrive-grid.html
- test/fixtures/admin-gdrive.html
- test/mocks/fetchMock.js
> fix: release 20240528

- src/extension/module.js
> fix(bulk): js error after bulk operation

- src/extension/background.js
- src/extension/utils.js
- test/extension/utils.test.js
- test/mocks/fetchMock.js
> fix: ignore originalSite if single match

- src/extension/background.js
- src/extension/manifest.json
This PR is in tandem with https://github.com/adobe/aem-sidekick/pull/230
> feat: project migration

- package-lock.json
- package.json
- src/extension/module.js
- src/extension/utils.js
- src/extension/view-doc-source/js/blocks.js
- src/extension/view-doc-source/js/ui.js
- src/extension/view/json/json.js
- test/extension/utils.test.js
- test/view-doc-source/fixtures/blocks-table.html
- test/view-doc-source/fixtures/single-table.html
> Release 2024-09-03

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko/messages.json
- src/extension/_locales/pt_BR/messages.json
- src/extension/_locales/zh_CN/messages.json
- src/extension/_locales/zh_TW/messages.json
- src/extension/background.js
- src/extension/options.html
- src/extension/options.js
- src/extension/utils.js
- test/extension/utils.test.js
- test/mocks/chromeMock.js
> feat(options): do not use giturl anymore

- docs/config.schema.json
- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/es/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko/messages.json
- src/extension/_locales/pt_BR/messages.json
- src/extension/_locales/zh_CN/messages.json
- src/extension/_locales/zh_TW/messages.json
- src/extension/app.css
- src/extension/background.js
- src/extension/module.js
- src/extension/options.html
- src/extension/options.js
- src/extension/utils.js
- test/extension/utils.test.js
- test/fixtures/401.html
- test/fixtures/403.html
- test/mocks/chromeMock.js
- test/module.test.js
> chore: release-20240913

- package-lock.json
- package.json
- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/_locales/fr/messages.json
- src/extension/_locales/it/messages.json
- src/extension/_locales/ja/messages.json
- src/extension/_locales/ko/messages.json
- src/extension/_locales/pt_BR/messages.json
- src/extension/_locales/zh_CN/messages.json
- src/extension/_locales/zh_TW/messages.json
- src/extension/module.js
- test/bulk-info.test.js
- test/bulk-preview.test.js
- test/edit-preview.test.js
- test/fixtures/admin-sharepoint-chinese-grid.html
- test/fixtures/admin-sharepoint-chinese.html
- test/utils.js
> chore(release): 2024-09-24

- src/extension/_locales/en/messages.json
- test/module.test.js
> fix: handle status 400

- src/extension/view/json/json.js
> fix(json): never load from cache

- src/extension/module.js
- src/extension/utils.js
- test/SidekickTest.js
- test/delete.test.js
- test/login.test.js
- test/logout.test.js
- test/module.test.js
- test/unpublish.test.js
> fix: translations update, cookie-less auth and v7 conflicts

- package-lock.json
- package.json
- src/extension/utils.js
- test/extension/utils.test.js
Backport of https://github.com/adobe/aem-sidekick/pull/516
> fix: Do not inject admin token for requests originatin on da.live

- src/extension/_locales/es/messages.json
- src/extension/module.js
- test/module.test.js
> Release 20250417

- src/extension/module.js
- test/bulk-preview.test.js
- test/fixtures/admin-sharepoint-grid.html
- test/fixtures/admin-sharepoint.html
> fix(bulk): selection no longer detected in sharepoint

- src/extension/background.js
- src/extension/sidekick.js
- src/extension/utils.js
Append ` AEMSidekick/{version}` to the `user-agent` header when communicating with the admin API.
> fix: instrument user agent
